# Generated by Django 5.0.6 on 2024-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('hr_manager', 'HR Manager'), ('programmer', 'Programmer'), ('seller', 'Seller'), ('cashier', 'Cashier'), ('driver', 'Driver'), ('cook', 'Cook')], max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
