# Generated by Django 5.0.6 on 2024-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Loyiha Menejeri'), ('hr_manager', 'HR Menejer'), ('backend_dev', 'Backend dasturchi'), ('frontend_dev', 'Frontend dasturchi'), ('devops', 'DevOps Injiner')], max_length=50),
        ),
    ]
