# Generated by Django 4.2.11 on 2024-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('MR', 'Loyiha Menejeri'), ('HR', 'HR Menejer'), ('BC', 'Backend dasturchi'), ('FR', 'Frontend dasturchi'), ('DI', 'DevOps Injiner')], max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('about', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
